language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION='Django>=1.11,<2.0'
  - DJANGO_VERSION='Django>=2.0,<2.1'
  - DJANGO_VERSION='Django>=2.1,<2.2'
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION='Django>=2.0,<2.1'
    - python: "2.7"
      env: DJANGO_VERSION='Django>=2.1,<2.2'
    - python: "2.7"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.4"
      env: DJANGO_VERSION='Django>=2.1,<2.2'
    - python: "2.7"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

install:
  - pip install -q $DJANGO_VERSION
  - pip install tox coveralls flake8

script:
  - coverage erase
  - if [[ $(python -c 'import sys; print("0" if sys.version_info < (2, 7) else "1")') == "1" ]]; then flake8 --ignore=E501; fi
  - PYTHONPATH=. coverage run -p example/run_tests.py
  - PYTHONPATH=. coverage run -p example/run_tests.py example.settings_no_debug
after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    - goinnn@gmail.com
    - blag@users.noreply.github.com
